### ISSUE TITLE
Configuration missing from documentation

### ISSUE THREAD

**Issue by mike-s-83** [schmittjoh/JMSPaymentPaypalBundle#54]
Hello,

This is the first time I'm doing this, so take it easy if it isn't supposed to be reported as a bug...I'm just trying to help anyone else who may run into similar issues. 

The PayPal bundle is great, but following the instructions doesn't work straight away. The most important piece of information that I think was missing was adding the following parameters to the config.yml file:

parameters:
-->payment.paypal.username:    __username__
-->payment.paypal.password:    __password__
-->payment.paypal.signature:   __signature__

Then, further below, reference these parameters:

jms_payment_paypal:
-->username: %payment.paypal.username%
-->password: %payment.paypal.password%
-->signature:  %payment.paypal.signature%
-->debug: true # when true, connect to PayPal sandbox; uses kernel debug value when not specified
       

I hope this helps.

Michael

**Comment by regularjack** [comment]
Fixed in #79
