### ISSUE TITLE
Express Checkout PayerID is missing. 

### ISSUE THREAD

**Issue by gregbiv** [schmittjoh/JMSPaymentPaypalBundle#63]
Can't figure out how to complete paypal transaction. It always return me 10419.
What I have missed from docs?

PS.
in ExpressCheckoutPlugin.php on 189 
        // complete the transaction
        $data->set('paypal_payer_id', $details->body->get('PAYERID'));

The $details->body->get('PAYERID') is empty :(

**Comment by regularjack** [comment]
You need to set a `useraction=commit` parameter in the redirect URL. This is now [documented](http://jmspaymentpaypalbundle.readthedocs.io/en/stable/usage.html#useraction).
