### ISSUE TITLE
Compatibility issue with Symfony 2.6

### ISSUE THREAD

**Issue by ajeetvarma** [schmittjoh/JMSPaymentPaypalBundle#84]
I have integrated the bundle in symfony 2.6 and no problem came in integration . When i used after implemented with api access key, password and signature and put code as below -
            
             use JMS\Payment\CoreBundle\Form\ChoosePaymentMethodType;

              $config = [
		    'paypal_express_checkout' => [
		        'return_url' => $this->generateUrl('paypal_payment_create', ['id' => $order->getId(),],        UrlGeneratorInterface::ABSOLUTE_URL),
		        'cancel_url' => $this->generateUrl('paypal_order_show', ['id' => $order->getId(),], UrlGeneratorInterface::ABSOLUTE_URL),
		        'useraction' => 'commit',
		        'checkout_params' => ['PAYMENTREQUEST_0_PAYMENTREQUESTID' => $order->getId()],
		    ],
		];

		$form = $this->createForm(ChoosePaymentMethodType::class, null, [
		    'amount'          => $order->getAmount(),
		    'currency'        => 'USD',
		    'predefined_data' => $config,
		]);

Then i m getting error like this-

> Could not load type "JMS\Payment\CoreBundle\Form\ChoosePaymentMethodType"

The i search for this issue and found following links 

[Link1](http://stackoverflow.com/questions/10346683/getting-error-could-not-load-type-jms-choose-payment-method-with-symfony2-jms)
[Link2](https://github.com/schmittjoh/JMSPaymentCoreBundle/issues/32)

In those links i found that it is compatible only with Symfony 2.1.

If any way to work with symfony 2.6 ?

Please suggest me if anything i  can  .. 

Thanks a lot in advance ..

**Comment by regularjack** [comment]
For Symfony versions earlier than 3.0, you need to refer to the form by it's "alias" instead of the class. In the call to `createForm` use `'jms_choose_payment_method'` instead of `ChoosePaymentMethodType::class`.

**Comment by ajeetvarma** [comment]
Thanks a lot .. It works..
