### ISSUE TITLE
Paypal Order Customizing in extended Data

### ISSUE THREAD

**Issue by phiamo** [schmittjoh/JMSPaymentPaypalBundle#9]
Hi,
i really like your work,
now i was wondering why paypal sometimes shows order status on the left side and why i often dont see the amout ...
i was not investigating to deep, but i think extendedData would be the right place to integrate:
https://cms.paypal.com/us/cgi-bin/?cmd=_render-content&content_ID=developer/e_howto_api_ECCustomizing
these additional fields.

Porbably that maybe already done? i will have a closer look.
cheers phil

**Comment by regularjack** [comment]
This feature is now implemented. See the [documentation](http://jmspaymentpaypalbundle.readthedocs.io/en/stable/usage.html#checkout-params) for more information.
