### ISSUE TITLE
Class "" used for service "jms\payment\corebundle\command\generatekeycommand" cannot be found

### ISSUE THREAD

**Issue by jeremydu** [schmittjoh/JMSPaymentPaypalBundle#93]
Hello,

As inicate above in update or in 1st installation 

I have the error:
PHP Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Class "" used for service "jms\payment\corebundle\command\generatekeycommand" cannot be found. in /www/vendor/symfony/symfony/src
/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/AddConsoleCommandPass.php:40

jms/payment-core-bundle 1.4.0
jms/payment-paypal-bundle 1.2.0

Thank you in advance.

**Comment by regularjack** [comment]
Did you manage to solve it? I think the problem might be that the service definition doesn't specify the `class` attribute, here: https://github.com/schmittjoh/JMSPaymentCoreBundle/blob/master/Resources/config/commands.xml#L7

Could you try changing that line to:

```xml
        <service id="JMS\Payment\CoreBundle\Command\GenerateKeyCommand" class="JMS\Payment\CoreBundle\Command\GenerateKeyCommand">
```

Please let me know if that works. Thanks.

**Comment by jeremydu** [comment]
Thank you @regularjack , it works perfectly, go get a fix?

**Comment by regularjack** [comment]
Fixed in https://github.com/schmittjoh/JMSPaymentCoreBundle/pull/231

https://github.com/schmittjoh/JMSPaymentCoreBundle/releases/tag/1.4.1

Thanks for your help!
